name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          pip install --upgrade pip
          pip install PyGithub openai==0.28.0

      - name: Run ChatGPT review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/chatgpt_review.py \
            --pr-number ${{ github.event.pull_request.number }} \
            --repo "${{ github.repository }}"
